version: '3.3'

services:
  #  Zookeepers
  zookeeper:
    image: zookeeper:3.7.0
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      JVMFLAGS: -Xmx256m
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    volumes:
      - ./data/zookeeper:/data
      - ./data/zookeeper/logs:/datalog
    healthcheck:
      test: [ "CMD-SHELL", "echo ruok | nc -w 2 zookeeper 2181" ]
      interval: 5s
      timeout: 3s
      retries: 2
    logging:
      options:
        max-size: "512k"
        max-file: "10"
  zoonavigator:
    image: elkozmon/zoonavigator:latest
    restart: always
    ports:
      - 9000:9000
  #schema-registry
  schemaregistry:
    image: confluentinc/cp-schema-registry:6.2.0
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8085"
    ports:
      - 8085:8085
    logging:
      options:
        max-size: "512k"
        max-file: "10"
#kafka broker
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
      - schemaregistry
    ports:
      - "19092:19092"
      - "19192:19192"
      - "19999:19999"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_REMOTE:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_REMOTE://kafka-dev.saas-solinftec.com:19092,PLAINTEXT_HOST://localhost:19999,INTERNAL://172.101.85.146:19192
      KAFKA_BROKER_ID: 1
      KAFKA_BROKER_RACK: "r1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data1_0"
      KAFKA_JMX_PORT: 9991
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    volumes:
      - ./data/kafka/1_0:/var/lib/kafka/data1_0
    logging:
      options:
        max-size: "512k"
        max-file: "10"

  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
      - schemaregistry
    ports:
      - "29092:29092"
      - "29192:29192"
      - "29999:29999"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_REMOTE:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_REMOTE://kafka-dev.saas-solinftec.com:29092,PLAINTEXT_HOST://localhost:29999,INTERNAL://172.101.85.146:29192
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_RACK: "r2"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data2_0"
      KAFKA_JMX_PORT: 9991
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    volumes:
      - ./data/kafka/2_0:/var/lib/kafka/data2_0
    logging:
      options:
        max-size: "512k"
        max-file: "10"
  kafka3:
    image: confluentinc/cp-kafka:6.2.0
    depends_on:
      - zookeeper
      - schemaregistry
    ports:
      - "39092:39092"
      - "39192:39192"
      - "39999:39999"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_REMOTE:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9092,PLAINTEXT_REMOTE://kafka-dev.saas-solinftec.com:39092,PLAINTEXT_HOST://localhost:39999,INTERNAL://172.101.85.146:39192
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_RACK: "r3"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_SCHEMA_REGISTRY_URL: "schemaregistry:8085"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data3_0"
      KAFKA_JMX_PORT: 9991
      KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
    volumes:
      - ./data/kafka/3_0:/var/lib/kafka/data3_0
    logging:
      options:
        max-size: "512k"
        max-file: "10"
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka1:9092;kafka2:9092;kafka3:9092
      SCHEMAREGISTRY_CONNECT: http://schemaregistry:8085
    logging:
      options:
        max-size: "512k"
        max-file: "10"